preload = /home/moonsea/Pictures/abstract.png
# preload = /home/moonsea/Pictures/wallhaven-yx65mg_3840x2160.png
# preload = /home/moonsea/Pictures/dog.png
preload = /home/moonsea/Pictures/Patterns.png
wallpaper = HDMI-A-1,/home/moonsea/Pictures/Patterns.png
wallpaper = eDP-1,/home/moonsea/Pictures/abstract.png
