# preload = /home/moonsea/Pictures/wallhaven-9dpk3k_3840x2160.png
# preload = /home/moonsea/Pictures/abstract.png
# preload = /home/moonsea/Pictures/snowing_mountains.png
# preload = /home/moonsea/Pictures/car_design_black.png
 # preload = /home/moonsea/Pictures/Patterns.png
 preload = /home/moonsea/Pictures/solar_systems.png
 preload = /home/moonsea/Pictures/Johan_Christian_Dahl_-_View_of_Dresden_by_Moonlight_-_Google_Art_Project.jpg
wallpaper = HDMI-A-1,/home/moonsea/Pictures/Johan_Christian_Dahl_-_View_of_Dresden_by_Moonlight_-_Google_Art_Project.jpg
wallpaper = eDP-1,/home/moonsea/Pictures/solar_systems.png
