[gmail]
source        = imaps://yueqrgg@gmail.com@imap.gmail.com:992
source-cred-cmd = pass mail/gmail
source-cred-cmd = $HOME/.cache/msmtp/auth.sh
outgoing      = smtp://@smtp.gmail.com
outgoing-cred-cmd = pass mail/gmail
# # outgoing-cred-cmd = $HOME/.cache/msmtp/auth.sh
default       = "[Gmail]/All Mail"
from          = yueqr <yueqrgg@gmail.com>
cache-headers = true
postpone = "[Gmail]/Drafts"
copy-to = "[Gmail]/Sent Mail"
# # send-as-utc   = true
# # send-with-hostname = false

[qmail]

source        = imaps://essensea@qq.com@imap.qq.com:993
source-cred-cmd = pass show mail/qmail
outgoing      = smtp://essensea@qq.com@smtp.qq.com:587
outgoing-cred-cmd = pass show mail/qmail
from          = essensea <1036969856@qq.com>
cache-headers = true
send-as-utc   = true
